feat: upgrade purchase_order_address
Mint-System/Odoo-Apps-Purchase-Workflow pull request #2
Opened 2024-07-04 09:29 UTC by laszlokr

2024-07-05 06:48 UTC, janikvonrotz requested changes

2024-07-05 06:48 UTC, janikvonrotz commented on purchase_order_address/tests/TEST_INSTRUCTIONS.rst
RFQ should be sent to the `partner_order_id` by default.

2024-07-11 08:43 UTC, laszlokr commented on purchase_order_address/tests/TEST_INSTRUCTIONS.rst
@janikvonrotz Does it have to be set on the mail template?

2024-07-11 09:16 UTC, janikvonrotz commented on purchase_order_address/tests/TEST_INSTRUCTIONS.rst
@laszlokr I guess yes.

2024-07-11 09:16 UTC, janikvonrotz requested changes

2024-07-11 09:16 UTC, janikvonrotz commented on purchase_order_address/models/purchase_order.py
> +    def action_rfq_send(self):
I guess this method does not work and can be removed.

2024-07-11 09:34 UTC, laszlokr commented on purchase_order_address/tests/TEST_INSTRUCTIONS.rst
@janikvonrotz just to make sure we are on the same page. In the wiki this step is described as done manually https://www.odoo-wiki.org/purchase-order-address.html#erweiterung-konfigurieren
I think we even discussed it last week and you said this can be kept that way.

2024-07-12 06:42 UTC, janikvonrotz approved these changes

2024-07-12 12:41 UTC, merged