Mig17.0 purchase _requisition_send
Mint-System/Odoo-Apps-Purchase-Workflow pull request #30
Opened 2024-11-11 09:51 UTC by laszlokr

2024-11-12 15:55 UTC, janikvonrotz requested changes

2024-11-12 15:55 UTC, janikvonrotz commented on purchase_requisition_send/pyproject.toml
Why is this file always showing up?

2024-11-12 15:55 UTC, janikvonrotz commented on purchase_requisition_order_address/pyproject.toml
Same here.

2024-11-12 15:55 UTC, janikvonrotz commented on purchase_order_address/pyproject.toml
And here.

2024-11-13 11:53 UTC, laszlokr commented on purchase_requisition_send/pyproject.toml
Apparently it comes from here: 
https://github.com/Mint-System/Odoo-Apps-Purchase-Workflow/blob/ad3a97be7efcb782b25dd58f1bcc101962807570/.pre-commit-config.yaml#L41C2-L44C23

```
Run pre-commit in /home/laszlokr/work/mintsystem/Odoo-Build/addons/purchase_workflow
forbidden files......................................(no files to check)Skipped
en.po files cannot exist.............................(no files to check)Skipped
init pyproject.toml with whool...........................................Failed
- hook id: whool-init
- exit code: 1
- files were modified by this hook

pyproject.toml was generated or modified in purchase_requisition_send, purchase_order_address, purchase_requisition_order_address

```

2024-11-14 13:45 UTC, janikvonrotz commented on purchase_requisition_send/pyproject.toml
@laszlokr Can you remove the pre commit config form the 17.0 templates?

2024-11-14 13:51 UTC, laszlokr commented on purchase_requisition_send/pyproject.toml
@janikvonrotz I removed the whool-init hook in this repo and in the templates folder too

2024-11-18 10:45 UTC, janikvonrotz approved these changes

2024-11-28 09:07 UTC, merged